### ISSUE TITLE
bug: "if ... do ... else do ..." not parsed correctly

### ISSUE THREAD

**Issue by terickson001** [tree-sitter-grammars/tree-sitter-odin#16]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Describe the bug

The following code causes an error in the parser.
```odin
package main

main :: proc() {
	if true do bar()
	else do baz()
}
```

### Steps To Reproduce/Bad Parse Tree

```
(package_declaration) ; [1:1 - 12]
 (identifier) ; [1:9 - 12]
(procedure_declaration) ; [3:1 - 6:1]
 (identifier) ; [3:1 - 4]
 (procedure) ; [3:9 - 6:1]
  (parameters) ; [3:13 - 14]
  (block) ; [3:16 - 6:1]
   (if_statement) ; [4:2 - 5:14]
    condition: (boolean) ; [4:5 - 8]
     (call_expression) ; [4:13 - 17]
      function: (identifier) ; [4:13 - 15]
     (identifier) ; [5:7 - 8]
    consequence: (call_expression) ; [5:10 - 14]
     function: (identifier) ; [5:10 - 12]

```

### Expected Behavior/Parse Tree

I expected the parse tree to contain 2 `consequence`s and an `else_clause`

**Comment by amaanq** [comment]
thanks, this is now fixed
